# Generated by Django 3.0.3 on 2020-02-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_logger'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='strikes',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='logger',
            name='action',
            field=models.IntegerField(choices=[(0, 'Performed a moderation action.'), (1, 'Created an object.'), (2, 'Edited an object.'), (3, 'Logged in to the site.'), (4, 'Logged out of the site.'), (5, 'Browsing the site.')], default=5),
        ),
    ]
