# Generated by Django 3.0.3 on 2020-03-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_remove_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='times_flagged',
            field=models.IntegerField(default=0),
        ),
    ]
